# Generated by Django 5.0.6 on 2024-07-08 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SsdCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ejecuciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('timestamp_inicio', models.DateTimeField()),
                ('timestamp_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('automatizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_automations.catalogo')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_automations.dispositivos')),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrica_id', models.IntegerField()),
                ('valor', models.FloatField()),
                ('FechaRegistro', models.DateField()),
                ('HoraRegistro', models.TimeField()),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_automations.ejecuciones')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='memoria_ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_automations.memoria'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='resolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_automations.resolucion'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_automations.sistemaoperativo'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='ssd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_automations.ssdcapacidad'),
        ),
    ]
