# Generated by Django 5.0.6 on 2024-07-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_automations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacorametrica',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dispositivos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ejecuciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='memoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='metrica',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='resolucion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sistemaoperativo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ssdcapacidad',
            options={'managed': False},
        ),
    ]
