# Generated by Django 5.0.6 on 2024-06-23 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ambiente', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SsdCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('hora_programada', models.TimeField()),
                ('automatizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Ejecuciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('timestamp_inicio', models.DateTimeField()),
                ('timestamp_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('automatizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.catalogo')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dispositivos')),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrica_id', models.IntegerField()),
                ('valor', models.FloatField()),
                ('FechaRegistro', models.DateField()),
                ('HoraRegistro', models.TimeField()),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ejecuciones')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='memoria_ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.memoria'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='resolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.resolucion'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sistemaoperativo'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='ssd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ssdcapacidad'),
        ),
    ]
